<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Gowtham Katta" />


<title>Case Study One</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="CaseStudyOne.html">Case Study One</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Case Study One</h1>
<h4 class="author">Gowtham Katta</h4>
<h4 class="date">6/26/2021</h4>

</div>


<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>This RMarkdown is the analysis of the Breweries and Beers data sets, they contain Brewery ID, Brewery Name, City, State, Beer Name, Beer ID, ABV and IBU and Style of each beer, and its volume. This analysis will be comprehensive, covering most aspects of its descriptive statistics as well as a prediction algorithm. It will include answers to questions you might have, and will include visualizations to demonstrate major key points.</p>
</div>
<div id="including-plots" class="section level2">
<h2>Including Plots</h2>
<p>You can also embed plots, for example:</p>
<pre class="r"><code>library(magrittr)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.3     ✓ purrr   0.3.4
## ✓ tibble  3.1.1     ✓ stringr 1.4.0
## ✓ tidyr   1.1.3     ✓ forcats 0.5.1
## ✓ readr   1.4.0</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x tidyr::extract()   masks magrittr::extract()
## x dplyr::filter()    masks stats::filter()
## x dplyr::lag()       masks stats::lag()
## x purrr::set_names() masks magrittr::set_names()</code></pre>
<pre class="r"><code>library(class)
library(data.table)</code></pre>
<pre><code>## data.table 1.14.0 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com</code></pre>
<pre><code>## **********
## This installation of data.table has not detected OpenMP support. It should still work but in single-threaded mode.
## This is a Mac. Please read https://mac.r-project.org/openmp/. Please engage with Apple and ask them for support. Check r-datatable.com for updates, and our Mac instructions here: https://github.com/Rdatatable/data.table/wiki/Installation. After several years of many reports of installation problems on Mac, it&#39;s time to gingerly point out that there have been no similar problems on Windows or Linux.
## **********</code></pre>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     transpose</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, first, last</code></pre>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre class="r"><code>library(ggplot2)
library(e1071)
library(GGally)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre class="r"><code>Beers = read.csv(&quot;~/Desktop/MSDS/Github DDS/Unit 8 and 9 Case Study 1/Beers.csv&quot;)
Breweries = read.csv(&quot;~/Desktop/MSDS/Github DDS/Unit 8 and 9 Case Study 1/Breweries.csv&quot;)</code></pre>
<p>Question 1: How many breweries are present in each state?</p>
<p>Answer: After examining the summary statistics of each column in the breweries data set, I found that there are about 10 breweries per state, with a minimum of 1 and a maximum of 47 breweries in any given state. You may find a breakdown of each state and its brewery count below.</p>
<pre class="r"><code>summary(Breweries$State)</code></pre>
<pre><code>##    Length     Class      Mode 
##       558 character character</code></pre>
<pre class="r"><code>ggplot(Breweries, aes(x = State)) + geom_bar() + xlab(&quot;State&quot;) + 
  ylab(&quot;Number of Breweries&quot;) + ggtitle(&quot;Number of Breweries in each State&quot;) +
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = -0.5)</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Question 2: Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.</p>
<p>Answer: After merging the beer data set and the breweries data set, I found that the first 6 observations consisted of, in order, Ukiah Brewing Company, 4 observations of the Butternuts Beer and Ale company, and the Sleeping Lady Brewing Company, respectively.</p>
<pre class="r"><code>colnames(Breweries)[1] = c(&quot;Brewery_id&quot;)
Total &lt;- merge(Breweries, Beers, by = &quot;Brewery_id&quot;)
names(Total) = c(&quot;Brewery_id&quot;, &quot;BreweryName&quot;, &quot;City&quot;, &quot;State&quot;, &quot;BeerName&quot;, &quot;Beer_ID&quot;, &quot;ABV&quot;, &quot;IBU&quot;, &quot;Style&quot;, &quot;Ounces&quot;)

head(Total)</code></pre>
<pre><code>##   Brewery_id        BreweryName        City State      BeerName Beer_ID   ABV IBU
## 1          1 NorthGate Brewing  Minneapolis    MN       Pumpion    2689 0.060  38
## 2          1 NorthGate Brewing  Minneapolis    MN    Stronghold    2688 0.060  25
## 3          1 NorthGate Brewing  Minneapolis    MN   Parapet ESB    2687 0.056  47
## 4          1 NorthGate Brewing  Minneapolis    MN  Get Together    2692 0.045  50
## 5          1 NorthGate Brewing  Minneapolis    MN Maggie&#39;s Leap    2691 0.049  26
## 6          1 NorthGate Brewing  Minneapolis    MN    Wall&#39;s End    2690 0.048  19
##                                 Style Ounces
## 1                         Pumpkin Ale     16
## 2                     American Porter     16
## 3 Extra Special / Strong Bitter (ESB)     16
## 4                        American IPA     16
## 5                  Milk / Sweet Stout     16
## 6                   English Brown Ale     16</code></pre>
<pre class="r"><code>tail(Total)</code></pre>
<pre><code>##      Brewery_id                   BreweryName          City State                  BeerName
## 2405        556         Ukiah Brewing Company         Ukiah    CA             Pilsner Ukiah
## 2406        557       Butternuts Beer and Ale Garrattsville    NY         Porkslap Pale Ale
## 2407        557       Butternuts Beer and Ale Garrattsville    NY           Snapperhead IPA
## 2408        557       Butternuts Beer and Ale Garrattsville    NY         Moo Thunder Stout
## 2409        557       Butternuts Beer and Ale Garrattsville    NY  Heinnieweisse Weissebier
## 2410        558 Sleeping Lady Brewing Company     Anchorage    AK Urban Wilderness Pale Ale
##      Beer_ID   ABV IBU                   Style Ounces
## 2405      98 0.055  NA         German Pilsener     12
## 2406      49 0.043  NA American Pale Ale (APA)     12
## 2407      51 0.068  NA            American IPA     12
## 2408      50 0.049  NA      Milk / Sweet Stout     12
## 2409      52 0.049  NA              Hefeweizen     12
## 2410      30 0.049  NA        English Pale Ale     12</code></pre>
<p>Question 3: Address the missing values in each column.</p>
<p>Answer: By running a function which finds null values in the NewTotal data set, I found that the only columns to contain missing values were ABV and IBU. This could be a potential risk in any analysis using these features as it might lead to misleading, or unrepresentative, results. It would be wise to proceed with caution.</p>
<pre class="r"><code>colSums(is.na(Total))</code></pre>
<pre><code>##  Brewery_id BreweryName        City       State    BeerName     Beer_ID         ABV         IBU 
##           0           0           0           0           0           0          62        1005 
##       Style      Ounces 
##           0           0</code></pre>
<pre class="r"><code>NewTotal &lt;- na.omit(Total)</code></pre>
<p>Question 4: Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.</p>
<p>Answer: After comparing the median alcohol content and international bitterness unit for each state, I found that there were a few states, ME, WV, and CA, with a much higher ABV; ME and WV had a considerably higher IBU than the rest of the states. Again, this analysis is conducted after imputing a considerable amount of missing values, so this finding could change as a result of including those values.</p>
<pre class="r"><code>ABV &lt;- data.frame(NewTotal %&gt;% group_by(State) %&gt;% summarise(Median_ABV = median(ABV)))

ggplot(ABV, aes(x = State, y = Median_ABV*100)) + geom_bar(stat = &quot;identity&quot;) + 
  xlab(&quot;State&quot;) + ylab(&quot;Median ABV %&quot;) + ggtitle(&quot;Median ABV % in each State&quot;) + 
  geom_text(aes(label = Median_ABV*100), size=rel(1.75), vjust = -0.5) +
  theme(axis.text.x = element_text(size = 5.5))</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>sum(ABV$Median_ABV / 50)</code></pre>
<pre><code>## [1] 0.05564</code></pre>
<pre class="r"><code>IBU &lt;- data.frame(NewTotal %&gt;% group_by(State) %&gt;% summarise(Median_IBU = median(IBU)))
IBU</code></pre>
<pre><code>##    State Median_IBU
## 1     AK       46.0
## 2     AL       43.0
## 3     AR       39.0
## 4     AZ       20.5
## 5     CA       42.0
## 6     CO       40.0
## 7     CT       29.0
## 8     DC       47.5
## 9     DE       52.0
## 10    FL       55.0
## 11    GA       55.0
## 12    HI       22.5
## 13    IA       26.0
## 14    ID       39.0
## 15    IL       30.0
## 16    IN       33.0
## 17    KS       20.0
## 18    KY       31.5
## 19    LA       31.5
## 20    MA       35.0
## 21    MD       29.0
## 22    ME       61.0
## 23    MI       35.0
## 24    MN       44.5
## 25    MO       24.0
## 26    MS       45.0
## 27    MT       40.0
## 28    NC       33.5
## 29    ND       32.0
## 30    NE       35.0
## 31    NH       48.5
## 32    NJ       34.5
## 33    NM       51.0
## 34    NV       41.0
## 35    NY       47.0
## 36    OH       40.0
## 37    OK       35.0
## 38    OR       40.0
## 39    PA       30.0
## 40    RI       24.0
## 41    SC       30.0
## 42    TN       37.0
## 43    TX       33.0
## 44    UT       34.0
## 45    VA       42.0
## 46    VT       30.0
## 47    WA       38.0
## 48    WI       19.0
## 49    WV       57.5
## 50    WY       21.0</code></pre>
<pre class="r"><code>ggplot(IBU, aes(x = State, y = Median_IBU)) + geom_bar(stat = &quot;identity&quot;) + 
  xlab(&quot;State&quot;) + ylab(&quot;Median IBU&quot;) + ggtitle(&quot;Median IBU in each State&quot;) + 
  geom_text(aes(label = Median_IBU), size=rel(1.75), vjust = -0.5) + 
  theme(axis.text.x = element_text(size = 5.5))</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<pre class="r"><code>sum(IBU$Median_IBU / 50)</code></pre>
<pre><code>## [1] 36.98</code></pre>
<p>Question 5: Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?</p>
<p>Answer: The state with the maximum alcoholic (ABV) beer is Kentucky, with an ABV value of 0.125. The state with the most bitter (IBU) beer is Oregon, with an IBU value of 138; this finding does not include missing values. So, after running the same code on the data set with no missing values. I found Colorado to have the highest ABV with a value of 0.128 and Oregon to again have the highest IBU value of 138.</p>
<pre class="r"><code>NewTotal[which.max(NewTotal$ABV),]</code></pre>
<pre><code>##   Brewery_id               BreweryName       City State       BeerName Beer_ID   ABV IBU
## 9          2 Against the Grain Brewery Louisville    KY London Balling    2685 0.125  80
##                Style Ounces
## 9 English Barleywine     16</code></pre>
<pre class="r"><code>Total[which.max(Total$ABV),]</code></pre>
<pre><code>##     Brewery_id             BreweryName    City State
## 384         52 Upslope Brewing Company Boulder    CO
##                                                 BeerName Beer_ID   ABV IBU            Style
## 384 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale    2565 0.128  NA Quadrupel (Quad)
##     Ounces
## 384   19.2</code></pre>
<pre class="r"><code>NewTotal[which.max(NewTotal$IBU),]</code></pre>
<pre><code>##      Brewery_id             BreweryName    City State                  BeerName Beer_ID   ABV IBU
## 1857        375 Astoria Brewing Company Astoria    OR Bitter Bitch Imperial IPA     980 0.082 138
##                               Style Ounces
## 1857 American Double / Imperial IPA     12</code></pre>
<p>Question 6: Comment on the summary statistics and distribution of the ABV variable.</p>
<p>Answer: Using the Total, the data set including missing values, I found ABV to have a minimum value of 0.001, a maximum value of 0.128, the first 25% of the data to have a value of 0.05, the first 50% of the data to have a value of 0.056, and the first 75% of the data to have a value of 0.067. The Total data are relatively equally distributed with only a few out-liers. Using the imputed data set, I found ABV to have a minimum value of 0.027, a maximum value of 0.125, the first 25% of the data to have a value of 0.05, the first 50% of the data to have a value of 0.057, and the first 75% of the data to have a value of 0.068. The data are slightly skewed to the right, meaning that the data are not equally distributed.</p>
<pre class="r"><code>summary(NewTotal$ABV)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.02700 0.05000 0.05700 0.05991 0.06800 0.12500</code></pre>
<pre class="r"><code>ggplot(NewTotal, aes(x = &quot;&quot;, y = ABV * 100)) + geom_boxplot() + xlab(&quot;All States&quot;) + 
  ylab(&quot;ABV %&quot;) + ggtitle(&quot;Summary of ABV %&quot;)</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>ggplot(NewTotal, aes(x = &quot;&quot;, y = IBU)) + geom_boxplot() + xlab(&quot;All States&quot;) + 
  ylab(&quot;ABV %&quot;) + ggtitle(&quot;Summary of IBU&quot;)</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>Question 7: Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot. Make your best judgment of a relationship and EXPLAIN your answer.</p>
<p>Answer: After conducting a regression analysis on the potential relationship between the bitterness of the beer and its alcoholic content, there appears to be an association between the two variables. As we can see from the plot, as the bitterness of the beer increases the alcoholic content of the beer increases as well. After conducting a hypothesis test, we found that there seems to be a slight positive linear relationship between the bitterness of the beer and its alcoholic content. This relationship can only be inferred upon the ABV and IBU of the breweries included within the data, as any IBU below the minimum or maximum would be extrapolation, and therefore unrepresentative of the population of breweries and the ABV and IBU values of their beers.</p>
<pre class="r"><code>ggplot(NewTotal, aes(x = IBU, y = ABV)) + geom_point() + geom_smooth(method = lm) +
  xlab(&quot;IBU&quot;) + ylab(&quot;ABV&quot;) + ggtitle(&quot;IBU versus ABV &quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>cor(NewTotal$IBU, NewTotal$ABV, method = c(&quot;pearson&quot;))</code></pre>
<pre><code>## [1] 0.6706215</code></pre>
<p>Question 8: Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA). You decide to use KNN classification to investigate this relationship. Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.</p>
<p>Answer: Using KNN classifier, the model performed with an accuracy of 84%, a sensitivity of 87%, and a specificity of 80% to classify various beers as India Pale Ales or other types of Ale. We are 95% confident that any given value of IBU and ABV will be accurately predicted it as an India Pale Ale if it falls between the interval (0.80, 0.88). These statistics were found using a k value = 39.</p>
<pre class="r"><code>IPA &lt;- Total[Total$Style %like% &quot;IPA&quot;, ]

IPA &lt;- subset(IPA, select = c(IBU, ABV, Style))

IPA$Style = c(&quot;IPA&quot;)


Ale &lt;- Total[Total$Style %like% &quot;Ale&quot;, ]

Ale &lt;- Ale[!grepl(&quot;IPA&quot;, Ale$Style), ]

Ale &lt;- subset(Ale, select = c(IBU, ABV, Style))

Ale$Style = c(&quot;Ale&quot;)

TotalAle &lt;- rbind(IPA, Ale)


# Factorize variable style
TotalAle$Style &lt;- as.factor(TotalAle$Style)
str(TotalAle)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1534 obs. of  3 variables:
##  $ IBU  : int  50 68 65 68 85 100 100 42 NA NA ...
##  $ ABV  : num  0.045 0.08 0.06 0.076 0.075 0.08 0.08 0.063 0.097 0.077 ...
##  $ Style: Factor w/ 2 levels &quot;Ale&quot;,&quot;IPA&quot;: 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
<pre class="r"><code>TotalAle &lt;- na.omit(TotalAle)


# Generate training index from 70% of total data set

set.seed(1)
splitPerc = 0.70

TrainIndices = sample(1:nrow(TotalAle), splitPerc * nrow(TotalAle))
TrainAle = TotalAle[TrainIndices,]
TestAle = TotalAle[-TrainIndices,]

# Standardize

PreValues &lt;- preProcess(TrainAle, method = c(&quot;center&quot;, &quot;scale&quot;))
TrainAleC &lt;- predict(PreValues, TrainAle)
TestAleC &lt;- predict(PreValues, TestAle)


TrainAle &lt;- TrainAleC[, -3]
TestAle &lt;- TestAleC[, -3]

TrainAle1 &lt;- TrainAleC[, 3, drop = TRUE]
TestAle1 &lt;- TestAleC[, 3, drop = TRUE]

set.seed(1)

model &lt;- knn(train = TrainAle, test = TestAle, cl = TrainAle1, k = 39)
confusionMatrix(TestAle1, model)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction Ale IPA
##        Ale 137  25
##        IPA  20 102
##                                          
##                Accuracy : 0.8415         
##                  95% CI : (0.7938, 0.882)
##     No Information Rate : 0.5528         
##     P-Value [Acc &gt; NIR] : &lt;2e-16         
##                                          
##                   Kappa : 0.6783         
##                                          
##  Mcnemar&#39;s Test P-Value : 0.551          
##                                          
##             Sensitivity : 0.8726         
##             Specificity : 0.8031         
##          Pos Pred Value : 0.8457         
##          Neg Pred Value : 0.8361         
##              Prevalence : 0.5528         
##          Detection Rate : 0.4824         
##    Detection Prevalence : 0.5704         
##       Balanced Accuracy : 0.8379         
##                                          
##        &#39;Positive&#39; Class : Ale            
## </code></pre>
<p>Question 9: Knock their socks off! Find one other useful inference from the data that you feel Budweiser may be able to find value in. You must convince them why it is important and back up your conviction with appropriate statistical evidence.</p>
<p>Answer: Despite each region have a difference in annual temperature, with the Northeast having the lowest temperature of 48.55 and the South having the highest temperature of 62.27, the average ABV in each region were very similar. There was a small correlation though. The regions with the highest annual temperatures, the Midwest and the South, had slightly higher average ABV. Also, if we closely at the number of breweries in each region, the Northeast and the South have the lowest number of breweries. The regions with the smallest populations are in the Northeast and Midwest, which represent 17.1% and 20.8% of the population respectively. The regions with the largest populations are in the West and the South, which represent 23.9% and 38.3% of the population respectively. The Northeast has the smallest population and appears to have the least amount of land, so it makes sense that the region has the fewest number of breweries. However, the South has the largest population and appears to have a lot land. Maybe Budweiser should consider branching out more in the South?</p>
<pre class="r"><code># Organizing by Region

NewTotal2 &lt;- NewTotal

NewTotal2$Region &lt;- sapply(NewTotal2$State, 
                           function(x) {if_else(x %in% c(&quot; DE&quot;,&quot; DC&quot;,&quot; FL&quot;,&quot; GA&quot;,&quot; MD&quot;,&quot; NC&quot;,&quot; SC&quot;,&quot; VA&quot;,&quot; WV&quot;,&quot; AL&quot;, &quot; KY&quot;,&quot; MS&quot;,&quot; TN&quot;,&quot; AR&quot;,&quot; LA&quot;,&quot; OK&quot;,&quot; TX&quot;),
                                                &quot;South&quot;,
                                                if_else(x %in% c(&quot; CT&quot;,&quot; ME&quot;,&quot; MA&quot;,&quot; NH&quot;,&quot; RI&quot;,&quot; VT&quot;,&quot; NJ&quot;,&quot; NY&quot;,&quot; PA&quot;),
                                                        &quot;Northeast&quot;,
                                                        if_else(x %in% c(&quot; IN&quot;,&quot; IL&quot;,&quot; MI&quot;,&quot; OH&quot;,&quot; WI&quot;,&quot; IA&quot;,&quot; KS&quot;, &quot; MN&quot;,&quot; MO&quot;,&quot; NE&quot;, &quot; ND&quot;,&quot; SD&quot;),
                                                                &quot;Midwest&quot;,
                                                                if_else(x %in% c(&quot; AZ&quot;,&quot; CO&quot;,&quot; ID&quot;,&quot; NM&quot;,&quot; MT&quot;,&quot; UT&quot;,&quot; NV&quot;,&quot; WY&quot;,&quot; AK&quot;,&quot; CA&quot;, &quot; HI&quot;,&quot; OR&quot;,&quot; WA&quot;),
                                                                        &quot;West&quot;,
                                                                        &quot;Not Found&quot;))))
                           })

# Checking the data set

summary(NewTotal2)</code></pre>
<pre><code>##    Brewery_id    BreweryName            City              State             BeerName        
##  Min.   :  1.0   Length:1405        Length:1405        Length:1405        Length:1405       
##  1st Qu.: 95.0   Class :character   Class :character   Class :character   Class :character  
##  Median :198.0   Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :224.2                                                                              
##  3rd Qu.:351.0                                                                              
##  Max.   :547.0                                                                              
##     Beer_ID          ABV               IBU            Style               Ounces     
##  Min.   :   1   Min.   :0.02700   Min.   :  4.00   Length:1405        Min.   : 8.40  
##  1st Qu.: 772   1st Qu.:0.05000   1st Qu.: 21.00   Class :character   1st Qu.:12.00  
##  Median :1439   Median :0.05700   Median : 35.00   Mode  :character   Median :12.00  
##  Mean   :1415   Mean   :0.05991   Mean   : 42.71                      Mean   :13.51  
##  3rd Qu.:2069   3rd Qu.:0.06800   3rd Qu.: 64.00                      3rd Qu.:16.00  
##  Max.   :2692   Max.   :0.12500   Max.   :138.00                      Max.   :32.00  
##     Region         
##  Length:1405       
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
<pre class="r"><code>colSums(is.na(NewTotal2))</code></pre>
<pre><code>##  Brewery_id BreweryName        City       State    BeerName     Beer_ID         ABV         IBU 
##           0           0           0           0           0           0           0           0 
##       Style      Ounces      Region 
##           0           0           0</code></pre>
<pre class="r"><code># Data frame for annual temperatures in each state

Temperatures = data.frame(State = c(&quot; AL&quot;, &quot; AK&quot;, &quot; AZ&quot;, &quot; AR&quot;, &quot; CA&quot;, &quot; CO&quot;, &quot; CT&quot;, &quot; DE&quot;, 
                                    &quot; FL&quot;, &quot; GA&quot;, &quot; HI&quot;, &quot; ID&quot;, &quot; IL&quot;, &quot; IN&quot;, 
                                    &quot; IA&quot;, &quot; KS&quot;, &quot; KY&quot;, &quot; LA&quot;, &quot; ME&quot;, &quot; MD&quot;, &quot; MA&quot;, &quot; MI&quot;, 
                                    &quot; MN&quot;, &quot; MS&quot;, &quot; MO&quot;, &quot; MT&quot;, &quot; NE&quot;, &quot; NV&quot;, &quot; NH&quot;, &quot; NJ&quot;, 
                                    &quot; NM&quot;, &quot; NY&quot;, &quot; NC&quot;, &quot; ND&quot;, &quot; OH&quot;, &quot; OK&quot;, &quot; OR&quot;, 
                                    &quot; PA&quot;, &quot; RI&quot;, &quot; SC&quot;, &quot; SD&quot;, &quot; TN&quot;, &quot; TX&quot;, &quot; UT&quot;, 
                                    &quot; VT&quot;, &quot; VA&quot;, &quot; WA&quot;, &quot; WV&quot;, &quot; WI&quot;, &quot; WY&quot;), 
                          AnnualTemp = c(62.8, 26.6, 60.3, 60.4, 59.4, 45.1, 49.0, 55.3, 70.7, 63.5,
                                         70.0, 44.4, 51.8, 51.7, 47.8, 54.3, 55.6, 66.4, 41.0,
                                         54.2, 47.9, 44.4, 41.2, 63.4, 54.5, 42.7, 48.8, 49.9,
                                         43.8, 52.7, 53.4, 45.4, 59.0, 40.4, 50.7, 59.6,
                                         48.4, 48.8, 50.1, 62.4, 45.2, 57.6, 64.8, 48.6, 
                                         42.9, 55.1, 48.3, 51.8, 43.1, 42.0))

# Merge with the temperatures data frame
NewTotal2 &lt;- merge(NewTotal2, Temperatures, by = &quot;State&quot;)

# Comparing the number of breweries in each region with GGPairs

Compare = NewTotal2 %&gt;% filter(Region == &quot;South&quot; | Region == &quot;Northeast&quot; |
                                        Region == &quot;Midwest&quot; | Region == &quot;West&quot;)

Compare %&gt;% select(ABV, AnnualTemp, Region) %&gt;% ggpairs(aes(color = Region))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code># Number of Breweries in each region

ggplot(NewTotal2, aes(x = Region, fill = Region)) + geom_bar() + xlab(&quot;Regions&quot;) + 
  ylab(&quot;Number of Breweries&quot;) + ggtitle(&quot;Number of Breweries in each Region&quot;) +
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = -0.5)</code></pre>
<p><img src="CaseStudyOne_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<pre class="r"><code># Average annual temperature in each region numerically

AnnualTemp2 &lt;- data.frame(NewTotal2 %&gt;% group_by(Region) %&gt;% summarise(Mean_AnnualTemp = mean(AnnualTemp)))
AnnualTemp2</code></pre>
<pre><code>##      Region Mean_AnnualTemp
## 1   Midwest        48.54558
## 2 Northeast        47.28627
## 3     South        62.26715
## 4      West        50.35795</code></pre>
<pre class="r"><code># Average ABV in each region numerically

ABV2 &lt;- data.frame(NewTotal2 %&gt;% group_by(Region) %&gt;% summarise(Mean_ABV = mean(ABV*100)))
ABV2</code></pre>
<pre><code>##      Region Mean_ABV
## 1   Midwest 5.912601
## 2 Northeast 5.859804
## 3     South 6.020578
## 4      West 6.075686</code></pre>
<p>Summary of Findings:</p>
<p>The data tell an interesting story. There are about 10 breweries per state, with various states being above and below the median IBU and ABV values for their IPAs and other Ales. Based on the data, the most untapped markets would be those with the lowest IBU and ABV values for both their IPAs and Ales. However, this data contained a significant number of missing values, values which would be important to include if further statistical analyses were conducted using the same features. There is, in fact, enough statistically significant evidence to suggest an association between the IBU and ABV of the beers mentioned within the data. A classifier would be an easy way to confidently predict if any given beer was an IPA or another type of Ale. It is up to the stakeholders to solidify this determination, but there seems to be potential market for IPAs with a low IBU and ABV value. Under this market, the conditions, assuming all factors held even, would be predictable based on previous Ale markets.</p>
<p>It is up to the stakeholders to solidify this determination, but there seems to be potential market for IPAs with a low IBU and ABV value. Under this market, the conditions, assuming all factors held even, would be predictable based on previous Ale markets.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
